### ISSUE TITLE
"Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array" ?!!

### ISSUE THREAD

**Issue by crazyserb** [fiso64/slsk-batchdl#11] opened 2023-11-19 12:07 UTC
For some reason any sort of attempt to download or print the tracks from CSV list like this:

slsk-batchdl.exe -i list.csv --config "C:\slsk\slsk-batchdl.conf"

or

slsk-batchdl.exe -i list.csv --print tracks-full

Returns the following error:

`Parsing CSV track info
Using inferred columns: artist:"Artist", title:"Title".
Warning: No duration column found, results may be imprecise
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Program.ParseCsvIntoTrackInfo(String path, String artistCol, String trackCol, String lengthCol, String albumCol, String descCol, String ytIdCol, String timeUnit, Boolean ytParse)
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)`

My list looks just fine, with Artist and Title column, all entries in the CSV file using " as string delimiter, etc. As in, the list worked just fine in previous versions (before 1.5).

Any idea what's happening?

**Comment by fiso64** [comment] 2023-11-19 13:03
Just tried it with a csv file and it works for me. Can you send a sample file so I can reproduce?

**Comment by crazyserb** [comment] 2023-11-19 14:25
Sure, here's a short slice of the longer CSV, and it still fails with this one too.
[list.csv](https://github.com/fiso64/slsk-batchdl/files/13403482/list.csv)

I am also using it with these parameters in slsk-batchdl.conf (along with the user & pass)

-s 
--skip-mode "name" 
--pref-format "mp3" 
--format "mp3,wav,flac" 
--min-bitrate "256" 
--max-bitrate "320" 
--skip-not-found 
--remove-ft  
--search-timeout 6000 
--max-stale-time 30000 
--display "double" 
--print "tracks-full"

**Comment by fiso64** [comment] 2023-11-19 17:04
fixed in the newest release

**Comment by crazyserb** [comment] 2023-11-23 14:50
Seems fixed, thank you!

**Closed** 2023-11-23 14:50 UTC

**Comment by datesss** [comment] 2025-03-11 20:25
i'm getting this same error on version 2.4.2.0, i simplified the csv as much as possible and could not avoid the error.
